const Names = // needs to be capitalized
{ adjectives: [
    "Allergic", "Ancient", "Arcane",
    "Buggy", "Brutal", "Bald",
    "Cantankerous", "Crotchety", "Critical", "Charismatic", "Courageous", "Cowardly",
    "Deck of", "Dextrous", "Dastardly",
    "Gluten Free", "Generous",
    "Flaccid",
    "Gargantuan",
    "Heroic", "Huge",
    "Infected", "Intelligent",
    "Jovial",
    "Low Poly", "Long", "Lethargic", "Luxurious", "Large",
    "Mordenkainen's", "Moist", "Magical", "Misunderstood",
    "Nasty", "Natural",
    "Poopin'",
    "Rambunctious", "Regular",
    "Spaghetti", "Short", "Sentimental", "Spicy", "Strong", "Skrunkly", "Small",
    "Ugly",
    "Tasha's", "Tiny",
    "Valiant", "Vegan", "Vigorous", "Villanous",
    "Wondrous", "Wise", "Wild",
    "Xanathar's",
  ],
  nouns: [
    "Artificers", "Allies", "Advantages", "Apocalypse",
    "Bugs", "Barbarians", "Bards", "Battlemaps", "Baileys",
    "Creatures", "Clans", "Clerics", "Constitution", "Charsima", "Companions", "Colvilles",
    "Dice", "Dragonmarks", "Dexterity", "Druids", "Dungeon Masters",
    "Errors", "EdgeLords", "Efforts",
    "Familiars", "Fighters",
    "Gerblins", "Guards", "Gnolls",
    "Hits", "Humanoids", "Hex Crawls",
    "Iyengars", "Intelligence",
    "Johnsons",
    "Knights", 
    "Murderhobos", "Mercers", "Mulligans", "McElroys", "Monsters", "Mages", "Monks", "Mounts", "Modifiers", "Minis",
    "NPCs", "Neckbeards",
    "Oozes", "O'Briens",
    "Paladins", "Patrons", 
    "Quests", 
    "Rolls", "Rangers", "Riegels", "Rays", "Rests",
    "Sorcerers", "Strength",
    "Townsfolk", "Tokens",
    "Wizards", "Warlocks", "Wagons", "Wisdom", "Wild Shapes", "Westmarches", "Willinghams",
  ]
}

module.exports.Names = Names;
